version: 2.1

orbs:
  win: sandbox/windows-tools@dev:preview

jobs:
  windows-stuff:
    working_directory: c:\\\\cache
    executor: win/preview-default
    steps:
      - run: echo \"Welcome to Windows on CircleCI\"
      - run: systeminfo

workflows:
  workflow:
    jobs:
      - windows-stuff
